name: test modules

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install terramate
        uses: terramate-io/terramate-action@v1

      - name: Run generate tests
        shell: bash
        run: |
          while :
          do 
            terramate generate --detailed-exit-code
            status=$?
            if [ "${status}" -ne "2" ]; then
              exit ${status};
            fi
          done
